initialization:
  x_init: [-10.0, -10.0]
phase1:
  gamma: 0.00055
  max_iter: 300
  tol: 0.0001
phase2:
  init_params: 1
  expo_alpha: 0.25
  expo_lambda: 0.75
  mu: 1
  max_iter: 500
data:
  test_ray:
    - [1.0, 0.0]
    - [0.9985334138511238, 0.054138908585417526]
    - [0.9941379571543596, 0.10811901842394177]
    - [0.9868265225415261, 0.16178199655276473]
    - [0.9766205557100867, 0.21497044021102407]
    - [0.9635499925192229, 0.2675283385292208]
    - [0.9476531711828025, 0.31930153013598]
    - [0.9289767198167914, 0.37013815533991434]
    - [0.907575419670957, 0.4198891015602646]
    - [0.8835120444460229, 0.46840844069979015]
    - [0.8568571761675893, 0.5155538571770217]
    - [0.8276889981568906, 0.5611870653623824]
    - [0.7960930657056438, 0.6051742151937651]
    - [0.7621620551276365, 0.6473862847818277]
    - [0.7259954919231308, 0.6876994588534232]
    - [0.6876994588534233, 0.7259954919231308]
    - [0.6473862847818277, 0.7621620551276365]
    - [0.6051742151937651, 0.7960930657056438]
    - [0.5611870653623823, 0.8276889981568906]
    - [0.5155538571770217, 0.8568571761675893]
    - [0.46840844069979015, 0.8835120444460229]
    - [0.4198891015602646, 0.907575419670957]
    - [0.37013815533991434, 0.9289767198167914]
    - [0.31930153013597995, 0.9476531711828025]
    - [0.26752833852922075, 0.963549992519223]
    - [0.214970440211024, 0.9766205557100867]
    - [0.16178199655276462, 0.9868265225415261]
    - [0.10811901842394187, 0.9941379571543596]
    - [0.05413890858541761, 0.9985334138511238]
    - [0.0, 1.0]
