initialization:
  x_init: [-10.0, -10.0]
phase1:
  gamma: 0.00055
  max_iter: 300
  tol: 0.0001
phase2:
  init_params: 1
  expo_alpha: 0.25
  expo_lambda: 0.75
  mu: 1
  max_iter: 500
data:
  test_ray:
    - [1.0, 0.0]
    - [0.9965844930066698, 0.08257934547233232]
    - [0.9863613034027223, 0.1645945902807339]
    - [0.9694002659393304, 0.24548548714079912]
    - [0.9458172417006346, 0.32469946920468346]
    - [0.9157733266550574, 0.4016954246529694]
    - [0.8794737512064891, 0.4759473930370735]
    - [0.8371664782625285, 0.5469481581224268]
    - [0.7891405093963936, 0.6142127126896678]
    - [0.7357239106731316, 0.677281571625741]
    - [0.6772815716257411, 0.7357239106731316]
    - [0.6142127126896678, 0.7891405093963936]
    - [0.5469481581224269, 0.8371664782625285]
    - [0.4759473930370736, 0.8794737512064891]
    - [0.40169542465296953, 0.9157733266550574]
    - [0.32469946920468357, 0.9458172417006346]
    - [0.24548548714079924, 0.9694002659393304]
    - [0.16459459028073398, 0.9863613034027223]
    - [0.0825793454723324, 0.9965844930066698]
    - [0.0, 1.0]
