# Cấu hình khởi tạo
initialization:
  x_init: [-10.0, -10.0]


# Tham số giai đoạn 1 (Phase 1)
phase1:
  gamma: 0.001
  max_iter: 50
  tol: 1.0e-4

# Tham số giai đoạn 2 (Phase 2)
phase2:
  init_params: 0.75
  expo_alpha: 0.35
  expo_lambda: 0.75
  mu: 0.1
  max_iter: 200

# Dữ liệu Test Ray (Lưu dưới dạng list of lists)
data:
  test_ray:
    - [1.0, 0.0]
    - [0.9978589232386035, 0.06540312923014306]
    - [0.9914448613738104, 0.13052619222005157]
    - [0.9807852804032304, 0.19509032201612825]
    - [0.9659258262890683, 0.25881904510252074]
    - [0.9469301294951057, 0.32143946530316153]
    - [0.9238795325112867, 0.3826834323650898]
    - [0.8968727415326884, 0.44228869021900125]
    - [0.8660254037844387, 0.49999999999999994]
    - [0.8314696123025452, 0.5555702330196022]
    - [0.7933533402912353, 0.6087614290087205]
    - [0.7518398074789774, 0.6593458151000688]
    - [0.7071067811865476, 0.7071067811865476]
    - [0.659345815100069, 0.7518398074789773]
    - [0.6087614290087207, 0.7933533402912352]
    - [0.5555702330196024, 0.8314696123025451]
    - [0.5000000000000001, 0.8660254037844386]
    - [0.44228869021900147, 0.8968727415326883]
    - [0.38268343236508984, 0.9238795325112867]
    - [0.3214394653031617, 0.9469301294951056]
    - [0.25881904510252096, 0.9659258262890682]
    - [0.19509032201612833, 0.9807852804032304]
    - [0.1305261922200517, 0.9914448613738104]
    - [0.06540312923014327, 0.9978589232386035]
    - [0.0, 1.0]
