# Cấu hình khởi tạo
initialization:
  x_init: [-10.0, -10.0]


# Tham số giai đoạn 1 (Phase 1)
phase1:
  gamma: 0.001
  max_iter: 50
  tol: 1.0e-4

# Tham số giai đoạn 2 (Phase 2)
phase2:
  init_params: 0.75
  expo_alpha: 0.35
  expo_lambda: 0.75
  mu: 0.1
  max_iter: 200

# Dữ liệu Test Ray (Lưu dưới dạng list of lists)
data:
  test_ray:
    - [0.99678533, 0.08011867]
    - [0.9903591 , 0.13852387]
    - [0.98051368, 0.19645082]
    - [0.96728307, 0.25369953]
    - [0.95071296, 0.31007236]
    - [0.93086054, 0.36537467]
    - [0.90779436, 0.41941554]
    - [0.88159406, 0.47200839]
    - [0.85235008, 0.52297165]
    - [0.82016339, 0.57212936]
    - [0.78514512, 0.61931183]
    - [0.74741617, 0.66435614]
    - [0.70710678, 0.70710678]
    - [0.66435614, 0.74741617]
    - [0.61931183, 0.78514512]
    - [0.57212936, 0.82016339]
    - [0.52297165, 0.85235008]
    - [0.47200839, 0.88159406]
    - [0.41941554, 0.90779436]
    - [0.36537467, 0.93086054]
    - [0.31007236, 0.95071296]
    - [0.25369953, 0.96728307]
    - [0.19645082, 0.98051368]
    - [0.13852387, 0.9903591 ]
    - [0.08011867, 0.99678533]